name: CI

on:
  push:
  schedule:
      - cron: '0 0 * * *' # Once per day at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create a Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          test
          - 日本語化mod
        draft: false
        prerelease: false
